"""add_medical_facts

Revision ID: f27074ce1ef6
Revises: a61e405d2e31
Create Date: 2026-09-10 09:15:40

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f27074ce1ef6'
down_revision = 'a61e405d2e31'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'medication_fact',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('document_extraction_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('dosage', sa.String(), nullable=True),
        sa.Column('frequency', sa.String(), nullable=True),
        sa.Column('route', sa.String(), nullable=True),
        sa.Column('duration', sa.String(), nullable=True),
        sa.Column('instructions', sa.String(), nullable=True),
        sa.Column('source_text', sa.Text(), nullable=True),
        sa.Column('source_location', sa.String(), nullable=True),
        sa.Column('verification_status', sa.String(), nullable=False, server_default='unverified'),
        sa.Column('verified_by', sa.String(), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('verification_notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['document_extraction_id'], ['document_extractions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_fact_session_id'), 'medication_fact', ['session_id'], unique=False)
    op.create_index(op.f('ix_medication_fact_document_extraction_id'), 'medication_fact', ['document_extraction_id'], unique=False)
    op.create_index(op.f('ix_medication_fact_verification_status'), 'medication_fact', ['verification_status'], unique=False)

    op.create_table(
        'lab_fact',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('document_extraction_id', sa.String(), nullable=True),
        sa.Column('test_name', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('unit', sa.String(), nullable=True),
        sa.Column('reference_range', sa.String(), nullable=True),
        sa.Column('flag', sa.String(), nullable=True),
        sa.Column('observation_timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('source_text', sa.Text(), nullable=True),
        sa.Column('source_location', sa.String(), nullable=True),
        sa.Column('verification_status', sa.String(), nullable=False, server_default='unverified'),
        sa.Column('verified_by', sa.String(), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('verification_notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['document_extraction_id'], ['document_extractions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_fact_session_id'), 'lab_fact', ['session_id'], unique=False)
    op.create_index(op.f('ix_lab_fact_document_extraction_id'), 'lab_fact', ['document_extraction_id'], unique=False)
    op.create_index(op.f('ix_lab_fact_verification_status'), 'lab_fact', ['verification_status'], unique=False)

    op.create_table(
        'timeline_fact',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('source_type', sa.String(), nullable=False),
        sa.Column('source_id', sa.String(), nullable=True),
        sa.Column('source_field', sa.String(), nullable=True),
        sa.Column('fact_type', sa.String(), nullable=False),
        sa.Column('fact_data', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('timestamp_precision', sa.String(), nullable=True),
        sa.Column('is_approximate', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('source_text', sa.Text(), nullable=True),
        sa.Column('source_location', sa.String(), nullable=True),
        sa.Column('verification_status', sa.String(), nullable=False, server_default='unverified'),
        sa.Column('verified_by', sa.String(), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('verification_notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_fact_session_id'), 'timeline_fact', ['session_id'], unique=False)
    op.create_index(op.f('ix_timeline_fact_verification_status'), 'timeline_fact', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_fact_verification_status'), table_name='timeline_fact')
    op.drop_index(op.f('ix_timeline_fact_session_id'), table_name='timeline_fact')
    op.drop_table('timeline_fact')
    op.drop_index(op.f('ix_lab_fact_verification_status'), table_name='lab_fact')
    op.drop_index(op.f('ix_lab_fact_document_extraction_id'), table_name='lab_fact')
    op.drop_index(op.f('ix_lab_fact_session_id'), table_name='lab_fact')
    op.drop_table('lab_fact')
    op.drop_index(op.f('ix_medication_fact_verification_status'), table_name='medication_fact')
    op.drop_index(op.f('ix_medication_fact_document_extraction_id'), table_name='medication_fact')
    op.drop_index(op.f('ix_medication_fact_session_id'), table_name='medication_fact')
    op.drop_table('medication_fact')
    # ### end Alembic commands ###